[package]
name = "simsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
csv = "1.1.6"
kdam = "0.2.7"
serde = "1.0.145"
serde_json = "1.0.85"
